const TYPES = {
  STRING: {
    JS: 'string',
    RUST: 'String',
    PYTHON: 'str',
    JAVA: 'String',
    CSHARP: 'string',
    DART: 'String',
  },
  NUMBER: {
    JS: 'number',
    RUST: 'i32',
    PYTHON: 'int',
    JAVA: 'int',
    CSHARP: 'int',
    DART: 'int',
  },
  INTEGER: {
    JS: 'number',
    RUST: 'i32',
    PYTHON: 'int',
    JAVA: 'int',
    CSHARP: 'int',
    DART: 'int',
  },
  FLOAT: {
    JS: 'number',
    RUST: 'f32',
    PYTHON: 'float',
    JAVA: 'float',
    CSHARP: 'float',
    DART: 'double',
  },
  BOOLEAN: {
    JS: 'boolean',
    RUST: 'bool',
    PYTHON: 'bool',
    JAVA: 'boolean',
    CSHARP: 'bool',
    DART: 'bool',
  },
  ARRAY: {
    JS: 'Array',
    RUST: 'Vec',
    PYTHON: 'List',
    JAVA: 'List',
    CSHARP: 'List',
    DART: 'List',
  },
  OBJECT: {
    JS: 'Object',
    RUST: 'HashMap',
    PYTHON: 'Dict',
    JAVA: 'Map',
    CSHARP: 'Dictionary',
    DART: 'Map',
  },
  ANY: {
    JS: 'any',
    RUST: 'any',
    PYTHON: 'Any',
    JAVA: 'Object',
    CSHARP: 'object',
    DART: 'dynamic',
  },
  VOID: {
    JS: 'void',
    RUST: '()',
    PYTHON: 'None',
    JAVA: 'void',
    CSHARP: 'void',
    DART: 'void',
  },
  NULL: {
    JS: 'null',
    RUST: 'None',
    PYTHON: 'None',
    JAVA: 'null',
    CSHARP: 'null',
    DART: 'null',
  },
  UNDEFINED: {
    JS: 'undefined',
    RUST: 'None',
    PYTHON: 'None',
    JAVA: 'null',
    CSHARP: 'null',
    DART: 'null',
  },
  DATE: {
    JS: 'Date',
    RUST: 'DateTime',
    PYTHON: 'datetime',
    JAVA: 'Date',
    CSHARP: 'DateTime',
    DART: 'DateTime',
  },
  FUNCTION: {
    JS: 'Function',
    RUST: 'Fn',
    PYTHON: 'Callable',
    JAVA: 'Function',
    CSHARP: 'Func',
    DART: 'Function',
  },
  PROMISE: {
    JS: 'Promise',
    RUST: 'Future',
    PYTHON: 'Future',
    JAVA: 'Future',
    CSHARP: 'Task',
    DART: 'Future',
  },
};

export default TYPES;
